#!/usr/bin/zsh

load_secrets() {
  export GITHUB_TOKEN=$(op read op://Personal/pietro-pc-github-token/token)
  export GITHUB_REGISTRY_AUTH_TOKEN=$(op read op://Personal/pietro-pc-github-registry-auth-token/token)
}
